# Name of the GitHub Action workflow
name: Build and Push Docker image to Docker Hub

# Trigger the workflow when a push event occurs
on: push

jobs:
  # Define a job to push the Docker image to Docker Hub
  push_to_registry:
    name: Push Docker image to Docker Hub
    # Run this job on the latest version of Ubuntu
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Check out the repo
        uses: actions/checkout@v3
      
      # Step 2: Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # Docker Hub username from secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Docker Hub access token from secrets
    
      # Step 3: Create a short version of the commit SHA to use in the image tag
      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    
      # Step 4: Build the Docker image and push it to Docker Hub with two tags (short SHA and latest)
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./                        # Use the current directory as the Docker build context
          push: true                         # Push the image after building
          tags: |                            # Define tags for the Docker image
                lakindu54/docker-automation:${{ env.SHORT_SHA }}   # Tag with short SHA
                lakindu54/docker-automation:latest                 # Tag as latest
